### ISSUE TITLE
Cant start website locally

### ISSUE THREAD

**Issue by VadimCpp** [codesandcoffees/vuejs-landing-page#2]
The issue appears when trying to start website locally:

```bash
git clone https://github.com/codesandcoffees/vuejs-landing-page.git
...OK

cd vuejs-landing-page
...OK

yarn install
...OK

yarn start
...FAIL
```

Error log:

```bash
http://localhost:8080/

webpack result is served from /
content is served from /Users/vadimcpp/Education/vuejs-landing-page
404s will fallback to /index.html

Error: ENOENT: no such file or directory, open '/Users/vadimcpp/Education/vuejs-landing-page/node_modules/svgo/lib/svgo/../../.svgo.yml'
at Object.fs.openSync (fs.js:663:18)
at Object.fs.readFileSync (fs.js:568:33)
at module.exports (/Users/vadimcpp/Education/vuejs-landing-page/node_modules/svgo/lib/svgo/config.js:31:48)
at new module.exports (/Users/vadimcpp/Education/vuejs-landing-page/node_modules/svgo/lib/svgo.js:21:19)
at buf (/Users/vadimcpp/Education/vuejs-landing-page/node_modules/imagemin-svgo/index.js:16:15)
at /Users/vadimcpp/Education/vuejs-landing-page/node_modules/promise.pipe/index.js:25:18
at <anonymous>

```

Please fix it.

Local versions: 

yarn -v
1.3.2

OS X El Capitan
10.11.6

**Comment by iamdevlinph** [comment]
Hi.

This repository hasn't been touched for a while now. To add, I also do not have a mac to test this.

But I may or may not look into it (it might just be a dependency issue or what, regardless of OS)

**Comment by mouthzipper** [comment]
Known issues in one of the dependencies we are using. 
Fixed it by disabling:

reference: https://github.com/svg/svgo/issues/622
